/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO.PersonaDAO;
import Modelo.Persona;
import Vista.FrmMultas.Frm_Biblioteca;
import Vista.FrmMultas.Frm_Consultar;
import Vista.FrmMultas.Frm_EliminarMulta;
import Vista.FrmMultas.Frm_GenerarInforme;
import Vista.FrmMultas.Frm_Licencia;
import Vista.FrmMultas.Frm_RegistarMultas;
import Vista.FrmMultas.Frm_RegistrarAuto;
import Vista.FrmMultas.Frm_RegistrarPersona;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author timoa
 */
public class Frame_Menu_Login extends javax.swing.JFrame {

    Persona persona;
    private PersonaDAO personaD = new PersonaDAO("Datos");
   // private boolean verificarInicio = false;
    //private int posventana = -1;
    private long idPersona;
    private int Rol;

    /**
     * Creates new form Frame_Menu_Login
     */
    public Frame_Menu_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    public Frame_Menu_Login(long idPersona) {
        this.idPersona = idPersona;
        persona = (Persona) personaD.obtenerPersona(idPersona);
        if (idPersona == -1) {
            this.Rol = 1;
        } else {
            this.Rol = persona.getIdRol();
        }

        initComponents();
        this.setLocationRelativeTo(null);

        if (Rol == 1) {
            Boton_Multas1.setEnabled(false);
            csboton1.setEnabled(false);
            jTabbedPane.setSelectedIndex(2);
        }else{
            jTabbedPane.setSelectedIndex(1);
        }
        
    }

    public void Frame_Login(int roles) {
        new JFrm_Login(this, true, roles).setVisible(true);
    }

    public void FrmBiblioteca() {
        Frm_Biblioteca fm = new Frm_Biblioteca(this, true);
        fm.setVisible(true);

    }

    public void FrmConsultar() {
        Frm_Consultar fm = new Frm_Consultar(this, true);
        fm.setVisible(true);

    }
    
    public void FrmEliminarMulta() {
        Frm_EliminarMulta fm = new Frm_EliminarMulta(this, true);
        fm.setVisible(true);

    }

    public void FrmInforme() {
        Frm_GenerarInforme fm = new Frm_GenerarInforme(this, true);
        fm.setVisible(true);

    }

    public void FrmMultas(long idPersona) {
        Frm_RegistarMultas fm = new Frm_RegistarMultas(this, true, idPersona);
        fm.setVisible(true);

    }

    public void FrmAgente() {
        new Frm_RegistrarPersona(this, true, -1).setVisible(true);
    }
    
    public void FrmLicencia(){
        Frm_Licencia fm = new Frm_Licencia(this, true);
        fm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_Biblioteca = new javax.swing.JButton();
        Boton_Consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Boton_Multas1 = new javax.swing.JButton();
        Boton_Informe1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        csboton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Boton_Agentes = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        csboton2 = new javax.swing.JButton();
        Boton_Vehiculo = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Boton_Eliminar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Boton_Puntos = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setToolTipText("");
        jTabbedPane.setMinimumSize(new java.awt.Dimension(710, 602));
        jTabbedPane.setOpaque(true);
        jTabbedPane.setPreferredSize(new java.awt.Dimension(710, 602));
        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(710, 602));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("GESTOR DE MULTAS");

        Boton_Biblioteca.setOpaque(false);
        Boton_Biblioteca.setContentAreaFilled(false);
        Boton_Biblioteca.setBorderPainted(false);
        Boton_Biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/documentacion.png"))); // NOI18N
        Boton_Biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BibliotecaActionPerformed(evt);
            }
        });

        Boton_Consultar.setOpaque(false);
        Boton_Consultar.setContentAreaFilled(false);
        Boton_Consultar.setBorderPainted(false);
        Boton_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/investigacion.png"))); // NOI18N
        Boton_Consultar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Boton_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ConsultarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Biblioteca de multas");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Consultar e informar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(Boton_Consultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(Boton_Biblioteca))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Consultar)
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Biblioteca)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("ACCESO PUBLICO", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(710, 602));
        jPanel4.setPreferredSize(new java.awt.Dimension(1298, 351));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setText("GESTOR DE MULTAS");

        Boton_Multas1.setOpaque(false);
        Boton_Multas1.setContentAreaFilled(false);
        Boton_Multas1.setBorderPainted(false);
        Boton_Multas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/billete.png"))); // NOI18N
        Boton_Multas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Multas1ActionPerformed(evt);
            }
        });

        Boton_Informe1.setOpaque(false);
        Boton_Informe1.setContentAreaFilled(false);
        Boton_Informe1.setBorderPainted(false);
        Boton_Informe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/historial-de-trabajo.png"))); // NOI18N
        Boton_Informe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Informe1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Registrar multas");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Generar informe");

        csboton1.setOpaque(false); 
        csboton1.setContentAreaFilled(false); 
        csboton1.setBorderPainted(false);
        csboton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/boton-x.png"))); // NOI18N
        csboton1.setText("CERRAR SESION");
        csboton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csboton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel11))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(jLabel14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(Boton_Multas1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(jLabel16))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(Boton_Informe1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(csboton1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addGap(9, 9, 9)
                .addComponent(Boton_Multas1)
                .addGap(103, 103, 103)
                .addComponent(jLabel16)
                .addGap(9, 9, 9)
                .addComponent(Boton_Informe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(csboton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("ACCESO AGENTE", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(710, 602));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("GESTOR DE MULTAS");

        Boton_Agentes.setOpaque(false);
        Boton_Agentes.setContentAreaFilled(false);
        Boton_Agentes.setBorderPainted(false);
        Boton_Agentes.setBackground(new java.awt.Color(204, 204, 255));
        Boton_Agentes.setForeground(new java.awt.Color(204, 204, 255));
        Boton_Agentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/policia.png"))); // NOI18N
        Boton_Agentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AgentesActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Regisrar/Modificar/Eliminar Persona");

        csboton2.setOpaque(false);
        csboton2.setContentAreaFilled(false);
        csboton2.setBorderPainted(false);
        csboton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/boton-x.png"))); // NOI18N
        csboton2.setText("CERRAR SESION");
        csboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csboton2ActionPerformed(evt);
            }
        });

        Boton_Vehiculo.setOpaque(false);
        Boton_Vehiculo.setContentAreaFilled(false);
        Boton_Vehiculo.setBorderPainted(false);
        Boton_Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/coche (1).png"))); // NOI18N
        Boton_Vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VehiculoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Regisrar/Modificar/Eliminar Vehiculo");

        Boton_Eliminar.setOpaque(false); Boton_Eliminar.setContentAreaFilled(false); Boton_Eliminar.setBorderPainted(false);
        Boton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/borrar.png"))); // NOI18N
        Boton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EliminarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Eliminar Multa");

        Boton_Puntos.setOpaque(false);
        Boton_Puntos.setContentAreaFilled(false);
        Boton_Puntos.setBorderPainted(false);
        Boton_Puntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/cambiar.png"))); // NOI18N
        Boton_Puntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PuntosActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Cambiar Puntos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(csboton2)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(Boton_Agentes, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(Boton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel20)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Boton_Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(22, 22, 22)))))
                .addGap(18, 26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Agentes)
                    .addComponent(Boton_Vehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton_Puntos)
                    .addComponent(Boton_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(csboton2)
                .addContainerGap())
        );

        jTabbedPane.addTab("ACCESO ADMINISTRADOR", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_BibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BibliotecaActionPerformed
        // TODO add your handling code here:

        System.out.println(Rol);
        FrmBiblioteca();

    }//GEN-LAST:event_Boton_BibliotecaActionPerformed

    private void Boton_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ConsultarActionPerformed

        FrmConsultar();
    }//GEN-LAST:event_Boton_ConsultarActionPerformed

    private void Boton_Multas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Multas1ActionPerformed
        // TODO add your handling code here:
        FrmMultas(persona.getIdPersona());
    }//GEN-LAST:event_Boton_Multas1ActionPerformed

    private void Boton_Informe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Informe1ActionPerformed
        // TODO add your handling code here:
        FrmInforme();
    }//GEN-LAST:event_Boton_Informe1ActionPerformed

    private void Boton_AgentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AgentesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FrmAgente();
    }//GEN-LAST:event_Boton_AgentesActionPerformed

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        // TODO add your handling code here:
        if (jTabbedPane.getSelectedIndex() == 2) {
            if (Rol != 1) {
                this.dispose();
                Frame_Login(1);
            }
        } else if (jTabbedPane.getSelectedIndex() == 1) {
            if (Rol != 2 && Rol != 1) {
                this.dispose();
                Frame_Login(2);
            }
        }
        
    }//GEN-LAST:event_jTabbedPaneStateChanged

    private void csboton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csboton1ActionPerformed
        // TODO add your handling code here:
        int sel = (JOptionPane.showConfirmDialog(null, "Esta Seguro que desea salir", "CERRAR SESION", JOptionPane.YES_NO_OPTION));
        if (sel == 0) {
            this.dispose();
            new Frame_Menu_Login().setVisible(true);
        }
    }//GEN-LAST:event_csboton1ActionPerformed

    private void csboton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csboton2ActionPerformed
        // TODO add your handling code here:
        int sel = (JOptionPane.showConfirmDialog(null, "Esta Seguro que desea salir", "CERRAR SESION", JOptionPane.YES_NO_OPTION));
        if (sel == 0) {
            this.dispose();
            new Frame_Menu_Login().setVisible(true);
        }
    }//GEN-LAST:event_csboton2ActionPerformed

    private void Boton_VehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VehiculoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Frm_RegistrarAuto fip;
        fip = new Frm_RegistrarAuto((Frame) SwingUtilities.getWindowAncestor(this), true, 1);
        fip.setVisible(true);
    }//GEN-LAST:event_Boton_VehiculoActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        // TODO add your handling code here:
        FrmEliminarMulta();
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    private void Boton_PuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PuntosActionPerformed
        // TODO add your handling code here:
        FrmLicencia();
    }//GEN-LAST:event_Boton_PuntosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Menu_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agentes;
    private javax.swing.JButton Boton_Biblioteca;
    private javax.swing.JButton Boton_Consultar;
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Informe1;
    private javax.swing.JButton Boton_Multas1;
    private javax.swing.JButton Boton_Puntos;
    private javax.swing.JButton Boton_Vehiculo;
    private javax.swing.JButton csboton1;
    private javax.swing.JButton csboton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
