/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.FrmMultas.Frm_Biblioteca;
import Vista.FrmMultas.Frm_Consultar;
import Vista.FrmMultas.Frm_GenerarInforme;
import Vista.FrmMultas.Frm_RegistarMultas;
import Vista.FrmMultas.Frm_RegistrarPersona;
import javax.swing.JOptionPane;

/**
 *
 * @author timoa
 */
public class Frame_Menu_Login extends javax.swing.JFrame {

    private boolean verificarInicio = false;
    private int posventana = -1;
    private int Rol = -1;
    private String nombre; 

    /**
     * Creates new form Frame_Menu_Login
     */
    public Frame_Menu_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Frame_Menu_Login(int Rol, String nombre) {
        this.Rol = Rol;
        this.nombre = nombre;
        initComponents();
        this.setLocationRelativeTo(null);

        if (Rol == 1) {
            Boton_Multas1.setEnabled(false);
            csboton1.setEnabled(false);
        }
    }

    public void Frame_Login(int roles) {
        new JFrm_Login(this, true,roles).setVisible(true);
    }

    public void FrmBiblioteca() {
        Frm_Biblioteca fm = new Frm_Biblioteca(this, true);
        fm.setVisible(true);

    }

    public void FrmConsultar() {
        Frm_Consultar fm = new Frm_Consultar(this, true);
        fm.setVisible(true);

    }

    public void FrmInforme() {
        Frm_GenerarInforme fm = new Frm_GenerarInforme(this, true);
        fm.setVisible(true);

    }

    public void FrmMultas() {
        Frm_RegistarMultas fm = new Frm_RegistarMultas(this, true,nombre);
        fm.setVisible(true);

    }

    public void FrmAgente() {
        new Frm_RegistrarPersona(this, true, Rol).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Boton_Biblioteca = new javax.swing.JButton();
        Boton_Consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Boton_Multas1 = new javax.swing.JButton();
        Boton_Informe1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        csboton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Boton_Agentes2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        csboton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setToolTipText("");
        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("GESTOR DE MULTAS");

        Boton_Biblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/documentacion.png"))); // NOI18N
        Boton_Biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BibliotecaActionPerformed(evt);
            }
        });

        Boton_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/investigacion.png"))); // NOI18N
        Boton_Consultar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Boton_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ConsultarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Biblioteca de multas");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Consultar e informar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Boton_Consultar))
                        .addGap(215, 215, 215)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_Biblioteca)
                            .addComponent(jLabel2))))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Biblioteca)
                    .addComponent(Boton_Consultar))
                .addContainerGap())
        );

        jTabbedPane.addTab("ACCESO PUBLICO", jPanel1);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setText("GESTOR DE MULTAS");

        Boton_Multas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/billete.png"))); // NOI18N
        Boton_Multas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Multas1ActionPerformed(evt);
            }
        });

        Boton_Informe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/historial-de-trabajo.png"))); // NOI18N
        Boton_Informe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Informe1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Registrar multas");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Generar informe");

        csboton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/boton-x.png"))); // NOI18N
        csboton1.setText("CERRAR SESION");
        csboton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csboton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Boton_Multas1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(Boton_Informe1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(240, 240, 240))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(csboton1)
                .addGap(445, 445, 445))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Informe1)
                    .addComponent(Boton_Multas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(csboton1)
                .addContainerGap())
        );

        jTabbedPane.addTab("ACCESO AGENTE", jPanel4);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("GESTOR DE MULTAS");

        Boton_Agentes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/policia.png"))); // NOI18N
        Boton_Agentes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Agentes2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Regisrar agentes");

        csboton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/boton-x.png"))); // NOI18N
        csboton2.setText("CERRAR SESION");
        csboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csboton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(327, 327, 327))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csboton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Agentes2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(37, 37, 37)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_Agentes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(csboton2)
                .addContainerGap())
        );

        jTabbedPane.addTab("ACCESO ADMINISTRADOR", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_BibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BibliotecaActionPerformed
        // TODO add your handling code here:

        System.out.println(Rol);
        FrmBiblioteca();

    }//GEN-LAST:event_Boton_BibliotecaActionPerformed

    private void Boton_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ConsultarActionPerformed

        FrmConsultar();
    }//GEN-LAST:event_Boton_ConsultarActionPerformed

    private void Boton_Multas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Multas1ActionPerformed
        // TODO add your handling code here:

        FrmMultas();
    }//GEN-LAST:event_Boton_Multas1ActionPerformed

    private void Boton_Informe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Informe1ActionPerformed
        // TODO add your handling code here:

        FrmInforme();
    }//GEN-LAST:event_Boton_Informe1ActionPerformed

    private void Boton_Agentes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Agentes2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FrmAgente();
    }//GEN-LAST:event_Boton_Agentes2ActionPerformed

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        // TODO add your handling code here:
        /*if(!(jTabbedPane.getSelectedIndex() == 2 && Rol==1)){
           this.dispose();
           Frame_Login();
       }*/
        if (jTabbedPane.getSelectedIndex() == 2) {
            if (Rol != 1) {
                this.dispose();
                Frame_Login(1);
            }
        } else if (jTabbedPane.getSelectedIndex() == 1) {
            if (Rol != 2 && Rol != 1) {
                this.dispose();
                Frame_Login(2);
            }
        }
    }//GEN-LAST:event_jTabbedPaneStateChanged

    private void csboton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csboton1ActionPerformed
        // TODO add your handling code here:
        int sel = (JOptionPane.showConfirmDialog(null, "Esta Seguro que desea salir", "CERRAR SESION", JOptionPane.YES_NO_OPTION));
        if (sel == 0) {
            this.dispose();
            new Frame_Menu_Login().setVisible(true);
        }
    }//GEN-LAST:event_csboton1ActionPerformed

    private void csboton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csboton2ActionPerformed
        // TODO add your handling code here:
        int sel = (JOptionPane.showConfirmDialog(null, "Esta Seguro que desea salir", "CERRAR SESION", JOptionPane.YES_NO_OPTION));
        if (sel == 0) {
            this.dispose();
            new Frame_Menu_Login().setVisible(true);
        }
    }//GEN-LAST:event_csboton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Menu_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agentes2;
    private javax.swing.JButton Boton_Biblioteca;
    private javax.swing.JButton Boton_Consultar;
    private javax.swing.JButton Boton_Informe1;
    private javax.swing.JButton Boton_Multas1;
    private javax.swing.JButton csboton1;
    private javax.swing.JButton csboton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
