/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.FrmMultas;

import Controlador.DAO.MarcaDAO;
import Controlador.DAO.PersonaDAO;
import Controlador.DAO.VehiculoDAO;
import Controlador.ListaSimple;
import Controlador.Utilidades;
import Modelo.Persona;
import Modelo.Vehiculo;
import Vista.Frame_Menu_Login;
import Vista.Tablas.TablaVehiculos;
import Vista.Tablas.TablaVehiculosEstado;
import Vista.componentes.Componentes;
import java.awt.event.ItemEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * Autores: Eutimio Arévalo, James Romero
 */
public class Frm_RegistrarAuto extends javax.swing.JDialog {

    /**
     * Creates new form Frm_RegistrarAuto
     */
    PersonaDAO personaD = new PersonaDAO("Datos");
    MarcaDAO marcaD = new MarcaDAO("Componentes");
    TablaVehiculos modelo = new TablaVehiculos();
    TablaVehiculosEstado modeloEstado = new TablaVehiculosEstado();
    VehiculoDAO vehiculoD = new VehiculoDAO("Datos");
    ListaSimple lista = new ListaSimple();
    int rol;
    Persona persona;

    public Frm_RegistrarAuto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Componentes.cargarCombo(cbCedula, personaD.listar(), "cedula");
        Componentes.cargarCombo(cbMarca, marcaD.listar(), "nombre");
        lista = vehiculoD.listar();
        cargarTabla();
        this.setLocationRelativeTo(null);
    }

    public Frm_RegistrarAuto(java.awt.Frame parent, boolean modal, long idPersona) {
        super(parent, modal);
        initComponents();
        persona = (Persona) personaD.obtenerPersona(idPersona);
        Componentes.cargarCombo(cbCedula, personaD.listar(), "cedula");
        Componentes.cargarCombo(cbMarca, marcaD.listar(), "nombre");
        this.setLocationRelativeTo(null);
        if (persona == null) {
            this.rol = 1;

        } else if (persona.getIdRol() == 2) {
            this.rol = persona.getIdRol();
            lista = vehiculoD.listar();
            jButtonEditar.setVisible(false);
            jButtonEliminar.setVisible(false);
            lista = vehiculoD.obtenerListaPersona(true);
        }
        cargarTabla();
    }

    /**
     * El siguiete método permite dejar en blanco los campos de placa y color
     */
    public void limpiar() {
        tfPlaca.setText(null);
        tfColor.setText(null);
    }

    /**
     * El siguiete método permite cargar la tabla con los vehiculos según la
     * persona
     */
    public void cargarTabla() {
        System.out.println(this.rol);
        if (this.rol == 2) {
            modelo.setListaPersona(personaD);
            modelo.setListaVehiculos(lista);
            tbVehiculos.setModel(modelo);
            tbVehiculos.updateUI();
        } else if (this.rol == 1) {
            modeloEstado.setListaPersona(personaD);
            modeloEstado.setListaVehiculos(lista);
            tbVehiculos.setModel(modeloEstado);
            tbVehiculos.updateUI();
        }
    }

    /**
     * El siguiete método permite abrir el frame de multas
     */
    public void FrameMultas() {
        Frm_RegistarMultas fm = new Frm_RegistarMultas(null, true, persona.getIdPersona());
        fm.setVisible(true);
    }

    /**
     *El siguiete método permite abrir el frame del menú
     */
    public void FrameMenu() {
        Frame_Menu_Login fm = new Frame_Menu_Login(-1);
        fm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCedula = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfColor = new javax.swing.JTextField();
        cbMarca = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVehiculos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("DATOS DE LA PERSONA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Cédula:");

        cbCedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCedula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCedulaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        lbNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono:");

        lbTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Marca:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Color:");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Placa:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("DATOS DEL VEHÍCULO");

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/56.png"))); // NOI18N
        jButtonGuardar.setText(" Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/114.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        tbVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVehiculos);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/123.png"))); // NOI18N
        jButtonEditar.setText(" Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/167.png"))); // NOI18N
        jButtonEliminar.setText(" Eliminar");
        jButtonEliminar.setToolTipText("");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jButtonGuardar)
                            .addGap(73, 73, 73)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonEditar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSalir))
                                .addComponent(jLabel6)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(cbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(205, 205, 205)
                            .addComponent(jLabel4)
                            .addGap(20, 20, 20)
                            .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEliminar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El siguiete método permite mostrar los datos de la persona al seleccionar una cédula
     * @param evt 
     */
    private void cbCedulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCedulaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbCedula.getSelectedIndex() == 0) {
                lbNombre.setText("");
                lbApellido.setText("");
                lbTelefono.setText("");
                if (this.rol == 2) {
                    lista = vehiculoD.obtenerListaPersona(true);
                } else if (this.rol == 1) {
                    lista = vehiculoD.listar();
                }
                cargarTabla();
            } else {
                try {
                    Persona dato = (Persona) (Utilidades.obtenerDato(personaD.listar(), "cedula", cbCedula.getSelectedItem().toString()));
                    lbNombre.setText(dato.getNombre());
                    lbApellido.setText(dato.getApellido());
                    lbTelefono.setText(dato.getTelefono());
                    if (this.rol == 2) {
                        lista = vehiculoD.obtenerListaPersona(dato.getIdPersona(), true);
                    } else if (this.rol == 1) {
                        lista = vehiculoD.obtenerListaPersona(dato.getIdPersona());
                    }
                    cargarTabla();
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_cbCedulaItemStateChanged

    /**
     * El siguiete método permite guardar los datos del vehículo
     * @param evt 
     */
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (tfColor.getText().length() > 0 && tfPlaca.getText().length() > 0 && cbMarca.getSelectedIndex() != 0 && cbCedula.getSelectedIndex() != 0) {
            if (!Utilidades.datoRepetido(vehiculoD.listar(), "placa", tfPlaca.getText())) {
                vehiculoD.setVehiculo(null);
                Persona dato = (Persona) (Utilidades.obtenerDato(personaD.listar(), "cedula", cbCedula.getSelectedItem().toString()));
                vehiculoD.getVehiculo().setPlaca(tfPlaca.getText());
                vehiculoD.getVehiculo().setModelo(String.valueOf(cbMarca.getSelectedItem()));
                vehiculoD.getVehiculo().setColor(tfColor.getText());
                vehiculoD.getVehiculo().setIdPersona(dato.getIdPersona());
                if (vehiculoD.guardar(dato.getIdPersona())) {
                    JOptionPane.showConfirmDialog(null, "Se guardo correctamente");
                    limpiar();
                    if (this.rol == 2) {
                        lista = vehiculoD.obtenerListaPersona(dato.getIdPersona(), true);
                    } else if (this.rol == 1) {
                        lista = vehiculoD.listar();
                    }
                    cargarTabla();
                } else {
                    JOptionPane.showConfirmDialog(null, "No se pudo guardar");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los parametros");
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * El siguiete método permite abrir el frame menu si es administrador de lo contrario se abre el frame de multas
     * @param evt 
     */
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        if (rol == 2) {
            this.dispose();
            FrameMultas();
        } else if (rol == 1) {
            this.dispose();
            FrameMenu();
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * El siguiete método permite eliminar de forma lógica la cuenta del vehículo
     * @param evt 
     */
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tbVehiculos.getSelectedRow();
        if (fila >= 0) {
            Vehiculo temp = (Vehiculo) vehiculoD.listar().obtenerPorPosicion(fila);
            vehiculoD.cambiarEstado(temp.getIdVehiculo(), "Datos/Vehiculo.json");
            if (this.rol == 2) {
                lista = vehiculoD.obtenerListaPersona(temp.getIdPersona(), true);
            } else if (this.rol == 1) {
                lista = vehiculoD.listar();
            }
            cargarTabla();
        } else {
            JOptionPane.showConfirmDialog(null, "Seleccione la persona que desea eliminar");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * El siguiete método permite editar los datos del vehículo
     * @param evt 
     */
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int fila = tbVehiculos.getSelectedRow();
        if (fila >= 0) {
            Vehiculo vehiculo = (Vehiculo) lista.obtenerPorPosicion(fila);
            Vehiculo Tempvehiculo = new Vehiculo();
            if (tfColor.getText().length() > 0 && tfPlaca.getText().length() > 0 && cbMarca.getSelectedIndex() != 0) {
                System.out.println(vehiculo.getIdVehiculo());
                Tempvehiculo.setIdVehiculo(vehiculo.getIdVehiculo());
                Tempvehiculo.setIdPersona(vehiculo.getIdPersona());
                Tempvehiculo.setEstadoVehiculo(vehiculo.isEstadoVehiculo());
                Tempvehiculo.setPlaca(tfPlaca.getText());
                Tempvehiculo.setModelo(String.valueOf(cbMarca.getSelectedItem()));
                Tempvehiculo.setColor(tfColor.getText());
                System.out.println();
                if (vehiculoD.editar(Tempvehiculo.getIdVehiculo(), Tempvehiculo)) {
                    JOptionPane.showMessageDialog(null, "Se edito correctamente");
                    lista = vehiculoD.listar();
                    cargarTabla();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Llene todos los parametros");
            }

        } else {
            JOptionPane.showConfirmDialog(null, "Seleccione los datos del vehiculo que desea editar");
        }
    }
    
/*
    private void jButtonEliminarTipoActionPerformed(java.awt.event.ActionEvent evt) {

    }//GEN-LAST:event_jButtonEditarActionPerformed
*/
    /**
     * El siguiete método permite cargar los datos del vehículo al seleccionar un registro de la tabla
     * @param evt 
     */
    private void tbVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVehiculosMouseClicked
        int fila = tbVehiculos.getSelectedRow();
        if (fila >= 0) {
            Vehiculo vehiculo = (Vehiculo) lista.obtenerPorPosicion(fila);
            cbMarca.setSelectedIndex(Utilidades.obtenerPosicionDato(marcaD.listar(), "nombre", vehiculo.getModelo()) + 1);
            tfColor.setText(vehiculo.getColor());
            tfPlaca.setText(vehiculo.getPlaca());

        }
    }//GEN-LAST:event_tbVehiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistrarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistrarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistrarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistrarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_RegistrarAuto dialog = new Frm_RegistrarAuto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCedula;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JTable tbVehiculos;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfPlaca;
    // End of variables declaration//GEN-END:variables
}
